# Site settings
title: Xiangming Zeng 
email: xzengemail@gmail.com
url: https://xzenggit.github.io
description: "Xiangming Zeng Physical Oceanography Ocean Modeling"
skills: "Ocean Modeling - Machine Learning - Data Analysis"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Designed by Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/xzenggit
  - title: linkedin
    url: http://www.linkedin.com/in/zengx

# Postal address (add as many lines as necessary)
address:
  - line: 2800 Faucetter Dr. 
  - line: Jordan Hall 4133
  - line: Raleigh, NC 27606

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
